### ISSUE TITLE
Audio is written twice

### ISSUE THREAD

**Issue by genabotpub** [nwaldispuehl/java-lame#11]
Hello,

I tried to follow the provided example, but for some reason mp3 that is created is written twice (i.e. the audio includes the same sound twice).

Would appreciate any advise.
gen

**Comment by nwaldispuehl** [comment]
Hi genabotpub,

thank you for your inquiry!

This is the first time I heard about this issue, so I assume the problem lies in your specific implementation, or your input sound file (it might have been overwritten with its content doubled one time). I just added a test class with a working example so please have a look and check your code again.

If you still think the problem lies with the library please provide your code and input sound file.

Kind regards
n

**Comment by genabotpub** [comment]
Hi Nico,

Thank you very much for the prompt and comprehensive. The problem is indeed in my code - I am trying to solve it now.

By the way, thank you for creating such a useful library.
gen

**Comment by nwaldispuehl** [comment]
I'm glad I could help!

Also thanks for the appreciation, but I did not create it; I merely curate a modern version of it. It was created by the LAME[1] team, and Ken Händel[2] translated it from C to Java some years ago. :slightly_smiling_face: 

[1]https://sourceforge.net/projects/lame/
[2]https://sourceforge.net/projects/jsidplay2/
