### ISSUE TITLE
Cannot find maven dependency for this project

### ISSUE THREAD

**Issue by rushiRK** [nwaldispuehl/java-lame#17]
Can someone provide me the maven dependency for the jar so that I can use in my project ?

**Comment by nwaldispuehl** [comment]
Hi rushiRK,

there is no artefact of this project in the Maven Central (https://search.maven.org/) since I could not decide on the proper group name (and did not want to publish something with LAMEs `net.sourceforge.lame` group) but you can easily use it in your maven project with any of these methods:

- Build the JAR as per directions, then use the `mvn` command line tool to install it in your local repository (`~/.m2/repository`): https://maven.apache.org/general.html#importing-jars
- Slightly adapt the Gradle file so it can install the artefact to your local Maven repository on its own: https://docs.gradle.org/current/userguide/publishing_maven.html
- Fork the repository and submit the artefact to the Maven Central by yourself under your own group name (it's open source after all).

I might change the gradle file accordingly by myself later on.
